export const menu = [
    {
        id:1,
        title:'MAIN',
        listItem:[
            {
                id:1,
                title:'HomePage',
                url:'/',
                icon:'home.svg'
            },
            {
                id:2,
                title:'Profile',
                url:'/users/1',
                icon:'user.svg'
            },

        ]
    },
    {
        id:2,
        title:'LISTS',
        listItem:[
            {
                id:1,
                title:'Users',
                url:'/',
                icon:'user.svg'
            },
            {
                id:2,
                title:'Products',
                url:'/',
                icon:'basket.svg'
            },
            ,
            {
                id:3,
                title:'Orders',
                url:'/',
                icon:'orders.svg'
            }
            ,
            {
                id:4,
                title:'Posts',
                url:'/',
                icon:'posts.svg'
            }
        ]
    },
   {
       id:3,
       title:'GENERAL',
       listItem:[
        {
            id:1,
            title:'Elements',
            url:'/',
            icon:'elements.svg'
        },
        {
            id:2,
            title:'Notes',
            url:'/',
            icon:'notes.svg'
        },
        ,
        {
            id:3,
            title:'Forms',
            url:'/',
            icon:'forms.svg'
        }
        ,
        {
            id:4,
            title:'Calender',
            url:'/',
            icon:'calendar.svg'
        }
    ]

   } ,
   {
        id:4,
        title:'MAINTENANCE',
        listItem:[
            {
                id:1,
                title:'Settings',
                url:'/',
                icon:'settings.svg'
            },
            {
                id:2,
                title:'Backups',
                url:'/',
                icon:'backups.svg'
            },
        ]
   }
   ,{
         id:5,
         title:'ANALYTICS',
         listItem:[
            {
                id:1,
                title:'Charts',
                url:'/',
                icon:'chart.svg'
            },
            {
                id:2,
                title:'Logs',
                url:'/',
                icon:'logs.svg'
            },
        ]
   }
]